[settings]
minimum_release_age = "3d"
dotfiles.root = "~/ghq/github.com/asapoka/dotfiles"
dotfiles.default_mode = "symlink"
[env]
LANG = "ja_JP.UTF-8"

[bootstrap.repos]
"~/ghq/github.com/asapoka/dotfiles" = { url = "git@github.com:asapoka/dotfiles.git", ref = "master" }

[tasks.upgrade]
description = "upgrade all"
run = "mise self-update -y && mise up && mise prune -y && mise doctor"    

[tasks.winget-upgrade]
description="Winget でパッケージを更新"
run = "winget upgrade --all --accept-source-agreements"

[tools]
fd = "latest"
bat = "latest"
gh = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
sheldon = "latest"
fzf = "latest"
neovim = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"

[bootstrap.packages]
"winget:AgileBits.1Password" = "latest"
"winget:7zip.7zip" = "latest"
"winget:AdGuard.AdGuard" = "latest"
"winget:Tailscale.Tailscale" = "latest"
"winget:VideoLAN.VLC" = "latest"

[dotfiles]
"~/.config/mise" = "~/ghq/github.com/asapoka/dotfiles/mise"