[settings]
minimum_release_age = "3d"
dotfiles.root = "~/ghq/github.com/asapoka/dotfiles"
dotfiles.default_mode = "symlink"
[env]
LANG = "ja_JP.UTF-8"

[bootstrap.repos]
"~/ghq/github.com/asapoka/dotfiles" = { url = "git@github.com:asapoka/dotfiles.git", ref = "master" }

[tasks.upgrade]
description = "upgrade all"
run = "mise self-update -y && mise up && mise prune -y && mise doctor"    

[tasks.winget-upgrade]
description="Winget でパッケージを更新"
run = "winget upgrade --all --accept-source-agreements"

[tools]
fd = "latest"
bat = "latest"
gh = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
sheldon = "latest"
fzf = "latest"
neovim = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"
bottom = "latest"

[bootstrap.packages]
"winget:AgileBits.1Password" = "latest"
"winget:7zip.7zip" = "latest"
"winget:AdGuard.AdGuard" = "latest"
"winget:Tailscale.Tailscale" = "latest"
"winget:VideoLAN.VLC" = "latest"

"brew-cask:ghostty"   = "latest"
"brew-cask:1password"   = "latest"
"brew-cask:adguard"   = "latest"
"brew-cask:font-hackgen-nerd"   = "latest"
"brew-cask:google-drive"   = "latest"
"brew-cask:vlc"   = "latest"
"brew-cask:visual-studio-code"   = "latest"
"brew-cask:scansnap-home"   = "latest"
"brew-cask:google-japanese-ime"   = "latest"


[dotfiles]
"~/.config/mise" = "~/ghq/github.com/asapoka/dotfiles/config/mise"
"~/.gitconfig" = "~/ghq/github.com/asapoka/dotfiles/home/.gitconfig"
"~/.ripgreprc" = "~/ghq/github.com/asapoka/dotfiles/home/.ripgreprc"
"~/.config/starship.toml" = "~/ghq/github.com/asapoka/dotfiles/config/starship.toml"

[dotfiles."PowerShell_profile.ps1"]
source = "~/ghq/github.com/asapoka/dotfiles/config/powershell/Microsoft.PowerShell_profile.ps1"
variants = [
  { os = "windows", target = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1" },
]

[dotfiles."VSCode_profile.ps1"]
source = "~/ghq/github.com/asapoka/dotfiles/config/powershell/Microsoft.PowerShell_profile.ps1"
variants = [
  { os = "windows", target = "~/Documents/PowerShell/Microsoft.VSCode_profile.ps1" },
]

[dotfiles."sheldon/plugins.toml"]
source = "~/ghq/github.com/asapoka/dotfiles/config/sheldon/plugins.toml"
variants = [
  { os = "macos", target = "~/.config/sheldon/plugins.toml" },
  { os = "linux", target = "~/.config/sheldon/plugins.toml" },
]

[dotfiles."config/ghostty"]
source = "~/ghq/github.com/asapoka/dotfiles/config/ghostty/config.ghostty"
variants = [
  { os = "macos", target = "~/.config/ghostty/config.ghostty" },
]
