[tasks.upgrade]
description = "upgrade all"
run = "mise self-update -y && mise up && mise prune -y && mise doctor"    

[tasks.winget-upgrade]
description="Winget でパッケージを更新"
run = "winget upgrade --all --accept-source-agreements"

[tools]
fd = "latest"
bat = "latest"
gh = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
sheldon = "latest"
fzf = "latest"
neovim = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"
