[tasks.upgrade]
description = "upgrade all"
run = "brew upgrade && mise upgrade"    

[tasks.winget-upgrade]
description="Winget でパッケージを更新"
run = "winget upgrade --all --accept-source-agreements"

[tools]
fd = "latest"
bat = "latest"
gh = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
fzf = "latest"
neovim = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"

[tools."github:alacritty/alacritty"]
version = "latest"
[tools."github:alacritty/alacritty".platforms]
macos-arm64 = {asset_pattern = "Alacritty-v*.dmg"}
windows-x64 = {asset_pattern = "Alacritty-v*-installer.msi" }
