name: install windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: install
        run: cd PowerShell && ./install.ps1
